### ISSUE TITLE
Step by step instructions to use vulkan needed

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#1]
I have installed setup.py.

Can you provide the step by step instructions (show explicit commands) to running example.py?
This will aid beginners to learn to use of your python wrapper for vulkan.  The documentation in README.md is not enough to go by. 

I tried the below. Appreciate your guidance 
```
$ cd vulkan-master 
$ sudo python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating vulkan.egg-info
writing top-level names to vulkan.egg-info/top_level.txt
writing vulkan.egg-info/PKG-INFO
writing dependency_links to vulkan.egg-info/dependency_links.txt
writing requirements to vulkan.egg-info/requires.txt
writing manifest file 'vulkan.egg-info/SOURCES.txt'
reading manifest file 'vulkan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'vulkan.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/_cffi_build
copying _cffi_build/vulkan_build.py -> build/lib/_cffi_build
copying _cffi_build/__init__.py -> build/lib/_cffi_build
creating build/lib/vulkan
copying vulkan/__init__.py -> build/lib/vulkan
copying vulkan/_vulkan.py -> build/lib/vulkan
generating cffi module 'build/lib/vulkan/_vulkan.py'
already up-to-date
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/vulkan
copying build/lib/vulkan/__init__.py -> build/bdist.linux-x86_64/egg/vulkan
copying build/lib/vulkan/_vulkan.py -> build/bdist.linux-x86_64/egg/vulkan
creating build/bdist.linux-x86_64/egg/_cffi_build
copying build/lib/_cffi_build/vulkan_build.py -> build/bdist.linux-x86_64/egg/_cffi_build
copying build/lib/_cffi_build/__init__.py -> build/bdist.linux-x86_64/egg/_cffi_build
byte-compiling build/bdist.linux-x86_64/egg/vulkan/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/vulkan/_vulkan.py to _vulkan.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/_cffi_build/vulkan_build.py to vulkan_build.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/_cffi_build/__init__.py to __init__.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying vulkan.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vulkan.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vulkan.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vulkan.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vulkan.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
_cffi_build.__pycache__.vulkan_build.cpython-35: module references __file__
creating dist
creating 'dist/vulkan-1.3.0-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vulkan-1.3.0-py3.5.egg
creating /usr/local/lib/python3.5/dist-packages/vulkan-1.3.0-py3.5.egg
Extracting vulkan-1.3.0-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding vulkan 1.3.0 to easy-install.pth file

Installed /usr/local/lib/python3.5/dist-packages/vulkan-1.3.0-py3.5.egg
Processing dependencies for vulkan==1.3.0
Searching for cffi==1.10.0
Best match: cffi 1.10.0
Adding cffi 1.10.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for pycparser==2.17
Best match: pycparser 2.17
pycparser 2.17 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Finished processing dependencies for vulkan==1.3.0

$ cd generator
$ ls
fake_libc_include  generate.py  vk_platform.h  vk.xml  vulkan.h  vulkan.template.py
$ python3 generate.py 
Traceback (most recent call last):
  File "generate.py", line 5, in <module>
    import inflection
ImportError: No module named 'inflection'
$ sudo pip3 install inflection
[sudo] password for sunbear: 
The directory '$HOME/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '$HOME/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting inflection
Installing collected packages: inflection
Successfully installed inflection-0.3.1
$ python3 generate.py 
Traceback (most recent call last):
  File "generate.py", line 7, in <module>
    import xmltodict
ImportError: No module named 'xmltodict'
$ sudo pip3 install xmltodict
The directory '$HOME/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '$HOME/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting xmltodict
  Downloading xmltodict-0.10.2.tar.gz
Installing collected packages: xmltodict
  Running setup.py install for xmltodict ... done
Successfully installed xmltodict-0.10.2
$ python3 generate.py 
$ ls
fake_libc_include  generate.py  vk_platform.h  vk.xml  vulkan.h  vulkan.template.py
$ python3 vulkan.template.py 
  File "vulkan.template.py", line 115
    {% for _, enums in model.enums.items() %}
     ^
SyntaxError: invalid syntax

$ cd ../example/
$ ls
example.py  frag.spv  shader.frag  shader.vert  vert.spv
$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    import sdl2
ImportError: No module named 'sdl2'
$ pip3 install sdl2
Collecting sdl2
  Could not find a version that satisfies the requirement sdl2 (from versions: )
No matching distribution found for sdl2
$ pip3 install sdl
Collecting sdl
  Could not find a version that satisfies the requirement sdl (from versions: )
No matching distribution found for sdl

```

**Comment by realitix** [comment]
Hello @sunbearc22, 
Thank you for your interest, you are totally right, I have to add step by step instructions. I do that tomorrow. 
The module you need to install is pysdl2.

**Comment by realitix** [comment]
By the way, you don't need to run the generator, the generator must be runned only if you want to fix a bug in the wrapper. 
I will add a note about that too.

**Comment by realitix** [comment]
@sunbearc22 I have updated the README. Don't hesitate to tell me if you need more informations.

**Comment by sunbearc22** [comment]
Thanks. I will access it later today and look forward to try it. Hav pip3 installed pysdl2. I notice it's proven for python 3.2 but not yet got 3.5 which I am using. In any case, I am looking forward to try out your instructions today and keep u posted.

**Comment by realitix** [comment]
Don't worry, pysdl2 works with Python 3.5 and Python 3.6.

**Comment by sunbearc22** [comment]
$ python3 example/example.py
Traceback (most recent call last):
   File "example/example.py", line 9, in <module>
     from vulkan import *
   File 
"/usr/local/lib/python3.5/dist-packages/vulkan-1.3.0-py3.5.egg/vulkan/__init__.py", 
line 109, in <module>
     _lib = ffi.dlopen('libvulkan.so')
OSError: cannot load library 'libvulkan.so': libvulkan.so: cannot open 
shared object file: No such file or directory

Note, vulkan SDK is installed on my system. I have tested that and 
Vulkan SDK works. How do I tell your python wrapper where to find the 
vulkan SDK?

**Comment by realitix** [comment]
Strange, the wrapper uses `dlopen`. So your SDK is clearly not available.
You can set theses environments variables to help `dlopen` (but it shouldn't be needed) :

```
export LD_LIBRARY_PATH=<PathToSDK/Vulkan-LoaderAndValidationLayers/dbuild/loader>
export VK_LAYER_PATH=<PathToSDK/Vulkan-LoaderAndValidationLayers/dbuild/layers>
export VK_ICD_FILENAMES=<Path to icd/intel_icd.json>
```

**Comment by realitix** [comment]
Indeed you are rigth, I have a problem too without LD_LIBRARY_PATH.
I'm fixing it

**Comment by sunbearc22** [comment]
In the /Vulkan/VulkanSDK/1.0.42.2, I issued the following commands:

$ ls
build_examples.sh  build_tools.sh  doc       Getting_Started.html 
Release_Notes.html  setup-env.sh  via.html
build_samples.sh   config          examples  install samples             
source        x86_64
$ source setup-env.sh
$ printenv | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=$HOME/Vulkan/VulkanSDK/1.0.42.2/x86_64/lib:
$ printenv | grep VK_LAYER_PATH
VK_LAYER_PATH=$HOME/Vulkan/VulkanSDK/1.0.42.2/x86_64/etc/explicit_layer.d
$ printenv | grep VK_ICD_FILENAMES
$

Seems there isn't a path for the graphic card drivers but... success... :)

$ python3 example/example.py
availables extensions: ['VK_KHR_surface', 'VK_KHR_xcb_surface', 
'VK_KHR_wayland_surface', 'VK_KHR_xlib_surface', 'VK_EXT_debug_report', 
'VK_NV_external_memory_capabilities']

availables layers: ['VK_LAYER_GOOGLE_unique_objects', 
'VK_LAYER_LUNARG_monitor', 'VK_LAYER_GOOGLE_threading', 
'VK_LAYER_LUNARG_core_validation', 'VK_LAYER_LUNARG_vktrace', 
'VK_LAYER_LUNARG_parameter_validation', 
'VK_LAYER_LUNARG_object_tracker', 'VK_LAYER_LUNARG_screenshot', 
'VK_LAYER_LUNARG_swapchain', 'VK_LAYER_LUNARG_api_dump', 
'VK_LAYER_LUNARG_standard_validation']

Create Xlib surface
availables devices: ['GTX TITAN', 'Intel(R) HD Graphics 530 (Skylake GT2)']
selected device: GTX TITAN

2 available queue family
indice of selected queue families, graphic: 0, presentation: 0

availables device extensions: ['VK_KHR_swapchain', 'VK_NV_glsl_shader', 
'VK_KHR_sampler_mirror_clamp_to_edge', 'VK_NV_dedicated_allocation', 
'VK_NV_external_memory', 'VK_NVX_device_generated_commands']

Logical device and graphic queue successfully created

selected format: 44
3 available swapchain present modes
3 images view created
FPS: 66
FPS: 60
FPS: 60
FPS: 60
FPS: 60
FPS: 60

I needed to source the environment settings in setup-env.sh first and 
run the python3 example/example.py in the same terminal.

I noticed that appearance of the window is a bit jittery when I try to 
move it around. Do you know why? Also I can't resize the window. Is this 
due to setting in sdl2?

Thanks.

Next, what is the syntax for using your wrapper? Same as vulkan SDK? Is 
there any notes you can share?

**Comment by sunbearc22** [comment]
Thanks for reopening..

**Comment by realitix** [comment]
Thanks for all your tests. GTX TITAN nice!
In `example.py`, I don't focus on doing a good utilization of Vulkan or SDL, it's just to show it works.

I have reopened this issue because I have done a mistake when using `dlopen` and I have to explain a little bit how to use the api.

**Comment by realitix** [comment]
I will update the Readme tonight, meanwhile, you can look at `example.py`. If you want to talk to me, I am on IRC ##vulkan

**Comment by sunbearc22** [comment]
Thanks. Will have a go and keep you posted.

**Comment by realitix** [comment]
I have updated the Readme, can you take a look and tell me if it's ok or if you need more informations.

**Comment by sunbearc22** [comment]
_Suggested revisions:_

**API**

The vulkan wrapper gives you complete access to the Vulkan API, including extension functions.

**Code Convention:**

Similar to Vulkan, types like enumerations and structs are prefixed with Vk, enumeration values are prefixed with VK_ and functions are prefixed with vk. However, structs are represented as tuples, (please elaborate for the others)....

**Structs**

All structs must be initialized with keyword parameters. Here's an example(_you had a typo_). To create the Vulkan struct VKInstanceCreateInfo, in Vulkan we write:
```
typedef struct VkInstanceCreateInfo {
   VkStructureType sType;
   const void *pNext;
   VkInstanceCreateFlags flags; = 0
   const VkApplicationInfo* pApplicationInfo;
   uint32_t enabledLayerCount;
   const char* const* ppEnabledLayerNames;
   uint32_t enabledExtensionCount;
   const char* const* ppEnabledExtensionNames;
} VkInstanceCreateInfo;
```
The vulkan equivalent of the above code is : 
```
from vulkan import *

createInfo = VkInstanceCreateInfo(
    sType=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
    flags=0,
    pApplicationInfo=appInfo,
    enabledLayerCount=len(layers),
    ppEnabledLayerNames=layers
    enabledExtensionCount=len(extensions),
    ppEnabledExtensionNames=extensions,
)
```
Note that void terms/variables in Vulkan do not need to appear in vulkan. (_Is this correct?_)
_You wrote that you use list to represent struct, but you use () and in python this means a tuple. Also, does the order of the terms in the tuple matter? In your original code, you described extensions before layers. However, in Vulkan I notice it describes layer followed by extension. I reordered your description to follow Vulkan. Will it affect the rest of your code?_

**Comment by realitix** [comment]
Thanks a lot @sunbearc22, it's a high quality review!
I realize that I have badly explained some concepts. I will update the readme.
There is no tuple,  `VkInstanceCreateInfo()` is a function and parameters are just keyword arguments, the order doesn't matter. When I spoke about list, it's about `layers` and `extensions`. You don't have to create a CFFI object handling a C array, the wrapper will do it for you.
When you call `VkInstanceCreateInfo()`, behind the scene, it creates a **real** C struct `VkInstanceCreateInfo`. The wrapper exposes a function in order to transform parameters according to CFFI needs.

**Comment by realitix** [comment]
I have updated the README. I wait for your comments

**Comment by sunbearc22** [comment]
_Below are my suggested revisions. Thanks for considering them._

### **Code conventions**

Similar to Vulkan, structs are prefixed with Vk, enumeration values are prefixed with VK_ and functions are prefixed with vk. 

**Structs**
Vulkan struct creation is achieved in vulkan using python functions. For example, if you want to create the Vulkan struct VkInstanceCreateInfo, you must be initialized it with its keyword parameters. In vulkan, you will call the python function VkInstanceCreateInfo with named parameters as shown below.

 In C++ (Vulkan) we write:
```
VkInstanceCreateInfo instance_create_info = {
    VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, // sType
    nullptr, // pNext
    0, // flags
    &application_info, // *pApplicationInfo
    3, // enabledLayerCount
    &layers, // *ppEnabledLayerNames
    3, // enabledExtensionCount
    &extensions // *ppEnabledExtensionNames
};
```
Our vulkan wrapper equivalent of the above C++ code is :
```
import vulkan as vk

instance_create_info = vk.VkInstanceCreateInfo(
    sType=vk.VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
    pNext=None,
    flags=0,
    pApplicationInfo=application_info,
    enabledLayerCount=len(layers),
    ppEnabledLayerNames=layers,
    enabledExtensionCount=len(extensions),
    ppEnabledExtensionNames=extensions,
)
```
To create the struct, you must remember to pass all parameters at creation time. This includes the Vulkan layers and extensions denoted by `ppEnabledLayerNames` and `ppEnabledExtensionNames`, which vulkan is able to facilitate too. 

I hope my struct  example demonstrate to you how vulkan conveniently converts your python code into native C types.

_Notes_:

- The default value for all parameters is None so you could have omitted pNext (because its value is None).
- Order of parameters doesn't matter since they are keyword parameters.
- The C++ syntax is more risky because you must pass all parameters in specific order.

**Functions**

vulkan greatly simplifies the calling of functions. In Vulkan API, you have to explicitly write three kinds of function:

- functions that create nothing
- functions that create one object
- functions that create several objects

In vulkan, all these troubles goes away. vulkan will takes care of you and knows when to return None, an object or a list. Here are three examples:

```
# Create one object
instance = vk.vkCreateInstance(pCreateInfo=createInfo)

# Create a list of object
extensions = vk.vkEnumerateDeviceExtensionProperties(
    physicalDevice=physical_device,
    pLayerName=None)

# Return None
vk.vkQueuePresentKHR(presentation_queue, present_create)
```
Vulkan functions usually return a VkResult, which returns the success and error codes/states of the function. vulkan is pythonic and converts VkResult to exception: if the result is not VK_SUCCESS, an exception is raised. More elaboration is given in the next section.

**Exceptions**

- vulkan has two types of Exceptions, namely VkError or VkException. The VkError exception handles all the error codes reported by Vulkan's VkResult. The VkException exception handles all the success code reported by Vulkan's VkResult, except the VK_SUCCESS success code. 
- Exception names are pythonized: VK_NOT_READY -> VkNotReady.

**Constants**

All Vulkan constants are available in vulkan and it even provides some fancy constants like UINT64_MAX.

**Comment by realitix** [comment]
Nice I update tomorrow

**Comment by realitix** [comment]
@sunbearc22 I have updated the README, do you see others things to improve ?

**Comment by sunbearc22** [comment]
Not at the moment. I trust I will learn more as I progress and then 
suggest to you more documentations to add. Ok with you?

**Comment by realitix** [comment]
Perfect! I close the issue then.
Thanks

**Comment by sunbearc22** [comment]
Just noticed u have a typo for the word.


      Ressources. It should have Resources.

**Comment by realitix** [comment]
Ok I'm fixing it
