### ISSUE TITLE
Queue enumeration code incorrect in example

### ISSUE THREAD

**Issue by griffin2000** [realitix/vulkan#10]
The code as it was defined will get different values for queue_family_graphic_index and queue_family_present_index. Which I think is not valid.

To get the example to work I had to replace that code with this (based on pyVulcan example code)
```
support_presents = [-1] * len(queue_families)

for i, queue_family in enumerate(queue_families):
    support_presents[i] = vkGetPhysicalDeviceSurfaceSupportKHR(
        physicalDevice=physical_device,
        queueFamilyIndex=i,
        surface=surface)
    if (queue_family.queueFlags & VK_QUEUE_GRAPHICS_BIT):
        queue_family_graphic_index = i
    if queue_family.queueCount > 0 and support_presents[i]:
        queue_family_graphic_index = i
        queue_family_present_index = i
        break

if queue_family_present_index==-1:
    for i, v in enumerate(support_presents):
        if v == VK_TRUE:
            queue_family_present_index = i
```

**Comment by realitix** [comment]
Thanks @griffin2000 for opening this issue. Can you explain me where the current code fails ? What is the output of `queue_family_graphic_index`, `queue_family_present_index` with current code/with your new code.
My graphic card hasn't present queue family so indeed it can be bad here.

**Comment by griffin2000** [comment]
I get queue_family_graphic_index=0 and queue_family_present_index=1 with the ToT code. This results in a  blank screen for me.

It is valid to have different queues (as you set imageSharingMode to VK_SHARING_MODE_CONCURRENT when you create the swap chain). But, while I am not 100% sure, I think it will mean that the rendering happens on a different GPU than the present  (my laptop has built-in Intel GPU and an Nvidia GPU.) Hence why I get a blank screen.

**Comment by realitix** [comment]
I will take a look soon

**Comment by realitix** [comment]
I think the problem comes from the semaphore I use. Semaphore only works on a single queue and with presentation queue, you have to queue so we have to synchronize with another way.

**Comment by realitix** [comment]
I can force present queue index to be the same as graphic, that way it will work everytime. It's not important from my point of view because it's an exemple. What is important is that it works for everyone.
What do you think about that ?

**Comment by realitix** [comment]
I have fixed it in https://github.com/realitix/vulkan/commit/1201847c709eca86aadcea40de5e56bffd29b901. Can you try again ?

**Comment by realitix** [comment]
I close this issue now.
You can open it again if you still have the error.
