### ISSUE TITLE
Questions on heapIndex, flags and propertyFlags provided by pMemoryProperties.

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#11]
I have used the vkGetPhysicalDeviceMemoryProperties to obtain the memory properties of a specific physical device, i.e. GPU, and printed out the returned values.

```
    def _setPhysicalDevice(self):
        self.physical_device = self.physical_devices[0]
        self.physical_device_memory = vk.vkGetPhysicalDeviceMemoryProperties(
            self.physical_device)
        print('    view physical_devices[0] properties')
        self._printPhysicalDeviceMemoryProperties(self.physical_device_memory)

    @staticmethod
    def _printPhysicalDeviceMemoryProperties(memory):
        print('  Memory:')
        print('  -memoryTypeCount: {}'.format(memory.memoryTypeCount))
        print('  -memoryTypes[VK_MAX_MEMORY_TYPES]:')
        for n, i in enumerate(memory.memoryTypes):
            print('    -{}, propertyFlags: {}, heapIndex: {}'.format(
                n, i.propertyFlags, i.heapIndex))
            if n == memory.memoryTypeCount - 1: break
        print('  -memoryHeapCount: {}'.format(memory.memoryHeapCount))
        print('  -memoryHeaps[VK_MAX_MEMORY_HEAPS]:')
        size = 0
        for n, i in enumerate(memory.memoryHeaps):
            print('    -{}, size: {}, flags: {}'.format(n, i.size, i.flags))
            if i.flags == 1 and i.size:
                size += i.size
            if n == memory.memoryHeapCount - 1: break
        print('GPU memory size = ', size)
```

```
      Memory:
      -memoryTypeCount: 11
      -memoryTypes[VK_MAX_MEMORY_TYPES]:
        -0, propertyFlags: 0, heapIndex: 1
        -1, propertyFlags: 0, heapIndex: 1
        -2, propertyFlags: 0, heapIndex: 1
        -3, propertyFlags: 0, heapIndex: 1
        -4, propertyFlags: 0, heapIndex: 1
        -5, propertyFlags: 0, heapIndex: 1
        -6, propertyFlags: 0, heapIndex: 1
        -7, propertyFlags: 1, heapIndex: 0
        -8, propertyFlags: 1, heapIndex: 0
        -9, propertyFlags: 6, heapIndex: 1
        -10, propertyFlags: 14, heapIndex: 1
      -memoryHeapCount: 2
      -memoryHeaps[VK_MAX_MEMORY_HEAPS]:
        -0, size: 6442450944, flags: 1
        -1, size: 25186016256, flags: 0
```

Based on this output, I can see there are 2 memory heaps. 

- The 1st heap has flags=1 that indicates that it refers to the local device memory and it has 6442450944 bytes. I have checked with the GPU spec, the GPU is suppose to have 6.144GB Standard Memory Config. Despite of the ~298MB differences in memory, I think it is reasonable to conclude that "-0, size: 6442450944, flags: 1" refers to the GPU i am querying.

- The 2nd heap has a size of ~25.2GB and flags=0. Tomaka believes it refers to the available CPU RAM in my system. I can accept that given that it is less than the actual RAM capacity in my system. However, Vulkan spec did not describe this flag value. Can you tell me where you defined this in vulkan?

- For the array memoryTypes, I see its first seven elements propertyFlags has a value of 0. However, Vulkan spec did not describe such a [bitmask](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkMemoryType). Also, their heapIndex has a value 1. Are they referring to the 1st element of the array memoryHeaps. If so, should their corresponding propertyFlags=0x00000001? 

- The 8th and 9th elements of memoryTypes has a heapIndex of 0 and a propertyFlags of 1. Is this reasonable?

**Comment by sunbearc22** [comment]
I found out that:
- propertyFlags = 0 means a memory allocation that GPU cannot directly access, and therefor GPU won't have the fastest access to it as compared to the GPU accessing it's own/local memory.
- heapIndex = 1 refers to the 2nd element of the memoryHeaps array.
- it is reasonable for the 8th and 9th elements of memoryTypes has a heapIndex of 0 and a propertyFlags of 1 as it is pointing to the local memory of the GPU.

**Comment by realitix** [comment]
Thanks @sunbearc22 for theses explanations
