### ISSUE TITLE
Debug Callback does not work.

### ISSUE THREAD

**Issue by Berserker66** [realitix/vulkan#16]
Or at least it doesn't for me.

If we take the Vulkan Tutorial:
https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers#page_Message_callback

Then not removing the debug callback before destroying the instance should yield a debug output.

So we change the almost last line in the vulkan example to 
#vkDestroyDebugReportCallbackEXT(instance, callback, None)
So that we intentionally trip this debug message.

What I found is, that no debug message appears.

I've started investigating this as I noticed the debug callback function never executes in my own project, which makes debugging harder than it should be.

Should it matter, this is win10 64bit on amd graphics, with as of now recent drivers.

**Comment by realitix** [comment]
Hello @Berserker66,
I just tried and I get the good log `DEBUG: DebugReport Debug Report callbacks not removed before DestroyInstance`.

I know the debug callback works great because I use it a lot (on Windows 10 64 bits too).
I'm sorry to say it looks like a driver bug.

Can you try others vulkan demos to confirm that it's your driver ?

**Comment by Berserker66** [comment]
What would that "others vulkan demos" be? A link would likely help.

**Comment by realitix** [comment]
In the Vulkan SDK, you have some examples available and this repository is very good for demos: https://github.com/SaschaWillems/Vulkan

**Comment by Berserker66** [comment]
Well, too late for that, I went from AMD beta drivers I think 17.10 to 17.7 and now everything works just fine. Thanks for helping, though.

**Comment by realitix** [comment]
Nice! I close
