### ISSUE TITLE
How would one create a Vertex Buffer (vulkan memory management)?

### ISSUE THREAD

**Issue by ompadu** [realitix/vulkan#18]
Hello, I'm trying to extend the _vulkan_ example using [this tutorial](https://vulkan-tutorial.com/Vertex_buffers/Vertex_buffer_creation) and the VULK engine as a guide. It was all and good until I've hit a memcpy. I tryied to gain some insight looking at [vulk/vulkanobject.py, line 787](https://github.com/realitix/vulk/blob/6326795a47ab41ee4c7a37d2e69a8faf6f2087b0/vulk/vulkanobject.py#L787), but I can't make heads of tail of it. This is the specific block of code that contains the memcpy:

`void* data;`
`vkMapMemory(device, vertexBufferMemory, 0, bufferInfo.size, 0, &data);`
`memcpy(data, vertices.data(), (size_t) bufferInfo.size);`
`vkUnmapMemory(device, vertexBufferMemory);`

How does one manage memory with _vulkan_?

Thank you :)

**Comment by realitix** [comment]
Hello @ompadu !
Yes I faced this issue too, not so easy to memcpy with Python...

So you can find my solution here: https://github.com/realitix/vulk/blob/master/vulk/graphic/mesh.py#L160
I use numpy to store my vertices array and I can memcpy it with `numpy.copyto`. Like you can see, I tell numpy that the format is `uint8` to do it bit by bit.
I didn't test but I think you can use `cffi` to do it: https://cffi.readthedocs.io/en/latest/ref.html#ffi-memmove.

Did I answer well to your question or do you want more informations ?

**Comment by ompadu** [comment]
I didn't even think to use `numpy`. I'll go with that as I don't really have any direct `cffi `experience. Thank you :)

**Comment by realitix** [comment]
Good luck!
