### ISSUE TITLE
"Random" Value changes.

### ISSUE THREAD

**Issue by Berserker66** [realitix/vulkan#20]
So, not sure where the problem comes from but basically I tried to move the example to a bit more of an object oriented style and something broke, that the validation layers and other debugs are not catching.

When I run my example version, you end up with results like these:
https://i.imgur.com/vfqQriT.png
https://i.imgur.com/413Ij60.png
https://i.imgur.com/Y6Yx1yR.png

So seemingly random different errors and visual bugs.
Now I've looked at some of the variables, such as the "extent" structure changing the internal variables during initialization and creating invalid images or framebuffer etc. So I believe some pointer is pointing wrong and the wrong data is changed - somewhere. Also, when I run this, almost always at the end do I get 
"DEBUG: ObjectTracker Unable to remove SwapchainKHR obj 0x2. Was it created? Has it already been destroyed?"
And python.exe has stopped working. The interesting bit, is that the python crash only occurs when I include the SDL2 stuff, might be related.

So, if someone is up for trying to find the problem, I put it into this dropbox folder:
https://www.dropbox.com/sh/kra2lyi5qefdjwh/AABnGvmNFjs3voatE33w_Y84a?dl=0

**Comment by realitix** [comment]
Hello @Berserker66, is this issue directly related to the Vulkan wrapper or is it more a general question about Vulkan? If you need inspiration, you can take a look at my Vulk project.
I wait for your answer before digging deeper.

**Comment by Berserker66** [comment]
It *might* be related to the vulkan wrapper, as there is - as far as I can tell - pointer stuff going awry. I haven't yet found the actual source of the problem, as the validation layer[s] only tell the result of it, not the source.

**Comment by Berserker66** [comment]
I found the issue by now - turns out if you have nested vulkan structures, such as extent within a viewport and the outer structure can no longer be "named" - it gets garbage collected but takes any inner data still bound to it with it. So if you use a "self.extent" across a class, then if you use that within a vulkan structure that gets used and then discarded, then your self.extent is filled with undefined data afterwards.

**Comment by realitix** [comment]
Hello @Berserker66, indeed you have to keep a reference to the inner object. I faced the same issue in my Vulk project. I could add a weak reference directly in the wrapper, like that you wouldn't need to manage it yourself. What do you think about it?

**Comment by Berserker66** [comment]
Child objects persisting as long as their parent does is expected behaviour in Python, so I do think the reference should be added. If you don't want to add it for performance reasons, then at least a notice should be added to the readme, so that people don't end up trying to debug this issue for hours, like I did.

**Comment by realitix** [comment]
I misunderstood your problem, indeed it's more problematic that I though at first. I am talking with the cffi maintainer to see how to avoid this issue.

**Comment by realitix** [comment]
It shouldn't happen for cffi maitainers. So it may be something else. Can you show me (in a gist) only the small part of the code where you get this issue.

**Comment by Berserker66** [comment]
Hm I'll see if I can find one. Here is how this problem still manifests itself in my current project, in case that gives you an idea.

As I kept having random stuff in my extent, I made this as part of my main interface:

    extent = property(lambda self: VkExtent2D(*self.resolution))

If I comment that out and instead bind go back to : 

    self.extent = get_swap_extent(surface_capabilities)

Then I start getting errors like these again:

      File "*", line 415, in update
        z = package.zoom / (interface.extent.height)
    ZeroDivisionError: division by zero

Doesn't necessarily be 0, it can be just about any value.

**Comment by Berserker66** [comment]
Well, this is based on your example.
https://gist.github.com/anonymous/855bfef82dfa53a4fbbf612d83dcec62

Let it run and it some point during draw_frame it will notice that the extent got GCed.

**Comment by realitix** [comment]
Thanks for the reproducible code, I will look what's wrong.

**Comment by realitix** [comment]
After more tests, it works with cffi==1.9.1 and crash with cffi==1.10.0 so the bug comes from cffi. I have to check commits between theses two versions.

**Comment by realitix** [comment]
My research so far:

1.10.0 = KO
1.9.2 = KO
1.9.1 = OK

**Comment by realitix** [comment]
I found out the bug!

It's in this commit : https://bitbucket.org/cffi/cffi/commits/b6adad5f4ea343f515563917826b4c66e2705ac8

**Comment by realitix** [comment]
I have opened an issue on cffi bugtracker, we have to wait for Armin to answer.
Nice catch @Berserker66 !

https://bitbucket.org/cffi/cffi/issues/327/regression-from-191-to-192

**Comment by realitix** [comment]
@Berserker66 Arigato found the problem. In the wrapper, this line is wrong: https://github.com/realitix/vulkan/blob/master/vulkan/__init__.py#L1939

I will update it and check if it works. It's a major bug because it affects all objects created.

**Comment by Berserker66** [comment]
On the note of random errors. I my project I have the occasional validation layer complaint about not checking memory requirements before allocating. Yet I know this is done and this only happens when multi-threaded. I am fairly - though no guarantees - certain that this is not actually a fault on my part as it always succesfully allocates and runs and the only hint that anything goes "wrong" is the validation layer and I made sure the threadlock all "host synchronized" objects and calls.
Any chance that this is related? Or should I try and find a minimal case and report that?

**Comment by realitix** [comment]
I don't think that it's related but we'll see

**Comment by realitix** [comment]
I continue on this. I found out the part of the cffi code that creates this bug.

**Comment by realitix** [comment]
@Berserker66 I found out the problem: we were not returning a new struct but a child struct. Check this commit: https://github.com/realitix/vulkan/commit/608213158c79a4ecdb44395af77f2d138f1029ca

**Comment by Berserker66** [comment]
Interesting. My multithreaded issue is indeed its own issue then. I also know that it only happens on nvidia but I have no nvidia card to test the actual problem :(
My friend who has an nvidia doesn't really get useful bug reports back to me.

**Comment by realitix** [comment]
Since the child struct is allocated through the parent struct (by Vulkan SDK), it seems normal to clear it too. Can you show a minimal code for your multi-thread issue.

**Comment by Berserker66** [comment]
Can't look into it now as I'm not home, but in the long run it's a logistical issue, I need someone with nvidia to test my project every now and then, as it turns out almost everyone I know uses AMD graphics. It also isn't an open source project so that makes posting code a bit of an issue.

**Comment by sunbearc22** [comment]
I encountered the same issue too. Like to summarize my learning from @realitix and The Vulkan Tutorial on this matter to remind myself and benefit other users. 

_The lessons learnt_: 
1. **When defining [Common Object Types](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#fundamentals-common-objects) such as Offset, Extent and Rectangle, the syntax defined by Vulkan Spec. must be strictly followed.** Else, strange behaviors such as random changes in the values of the offset, extent or rectangle, after they have been allocated, can occur. Commit [6082131](https://github.com/realitix/vulkan/commit/608213158c79a4ecdb44395af77f2d138f1029ca) is an example.
2. _Why is it that undefined behaviour or crashes commonly happens in vulkan/Vulkan programming?_ Quoting the  [Vulkan Tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers):

> The Vulkan API is designed around the idea of minimal driver overhead and one of the manifestations of that goal is that there is very limited error checking in the API by default. **Even mistakes as simple as setting enumerations to incorrect values or passing null pointers to required parameters are generally not explicitly handled and will simply result in crashes or undefined behavior.** 

- Therefore, whenever a programmer encounters random crashes or undefined behaviour when executing a vulkan program, it is reasonable to treat these perplexing behaviours as a 1st level indication of wrong syntax or typo committed somewhere in the vulkan program.
