### ISSUE TITLE
Vulkan Memory Allocator

### ISSUE THREAD

**Issue by Berserker66** [realitix/vulkan#29]
There is a library for vulkan memory allocation management by GPU-Open
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
I keep seeing it recommended in various documentation and tutorials.
It feels like a nice fit for a python-vulkan module as it gives the option for simpler memory management, something that people using Python generally opted out of.

If possible, including this library or offering an optional extension would be fantastic (that is just my opinion, of course.)

**Comment by realitix** [comment]
Hello @Berserker66, indeed it's a nice library. From my point of view, it's better to create another wrapper dedicated to this library and to put `vulkan` as a dependancy. It seems very simple to wrap with cffi. I will take a look and wrap it when I have time. Thanks for the tips! I let this issue open to keep this in mind.

**Comment by realitix** [comment]
Hello @Berserker66,
I created a first wrapper of Vulkan Memory Allocator here: https://github.com/realitix/pyvma
It's a work in progress.

**Comment by Berserker66** [comment]
Thank you!
