### ISSUE TITLE
typo in example.py line 132, 133 

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#3]
I believe there is a typo in example.py line 132 & 133.
For Win32 window, it say:
```
sType=VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR,
hinstance=get_instance(wm_info.info.win.window),
```
Instead, I think It should be:
```
sType=VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR,
hinstance=get_instance(wm_info.info.win.hinstance),
```

**Comment by realitix** [comment]
I will test it on my Windows computer to be sure

**Comment by griffin2000** [comment]
There is also one on line 134: hwdn instead of hwnd

**Comment by realitix** [comment]
You can try on windows, it works now !
