### ISSUE TITLE
Auto-fill sType

### ISSUE THREAD

**Issue by Berserker66** [realitix/vulkan#33]
The sType has a default value. In the C/C++ version of vulkan, there is no such thing as a default structure value, so it has to be filled in manually. Since this wrapper uses keyword arguments anyway, it should be reasonable to make the default sType the default value for the sType kwarg, instead of None. Should, for some reason an overwrite or explicit sType be wished, this would still be possible as a keyword argument's default can easily be overwritten.

**Comment by realitix** [comment]
Hello @Berserker66, yes it's a nice feature. I will add it.
Did you see the answer on reddit ? Strange man...

**Comment by realitix** [comment]
Fixed by https://github.com/realitix/vulkan/commit/45927962466b6f19deaaadf79aca984fb4644f12
