### ISSUE TITLE
Count arguments of vulkan structures are not necessary

### ISSUE THREAD

**Issue by Berserker66** [realitix/vulkan#36]
extracted from a discussion from here: https://github.com/realitix/vulkan/issues/34#issuecomment-335897767

calling len() on the passed arguments to a vulkan function can be handled by this module internally, making passing a Count optional.

Original post follows:

Hm. By the same token though, should it not also work this way the other way around then?
You know, for consistency.
So in this example:

```
instance_create_info = vk.VkInstanceCreateInfo(
    sType=vk.VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
    pNext=None,
    flags=0,
    pApplicationInfo=application_info,
    enabledLayerCount=len(layers),
    ppEnabledLayerNames=layers,
    enabledExtensionCount=len(extensions),
    ppEnabledExtensionNames=extensions,
)
```
enabledLayerCount and enabledExtensionCount should then be automatic - or optional?

**Comment by realitix** [comment]
Fixed by https://github.com/realitix/vulkan/commit/dc566edf4412fc740956c9c6c5507835d257b958
