### ISSUE TITLE
vkQueuePresentKHR returned None

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#37]
Hi realitix,
Is the function `vkQueuePresentKHR` suppose to return `None` or `VkResult`? I was expecting the latter.

I am attempting the resizeable window tutorial of [Vulkan Tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation). I noticed that `vkQueuePresentKHR`  returns `None`.
```
        result = self.fnp['vkQueuePresentKHR'](self.present_queue, presentInfo)
        print('result = ',result)
 
        if result == VK_ERROR_OUT_OF_DATE_KHR or result == VK_SUBOPTIMAL_KHR:
            logging.error("Needs to recreate swapchain.!")
            self._recreateSwapChain()
        elif result != VK_SUCCESS:
            logging.error("Failed to present swapchain image!")

        vkQueueWaitIdle(self.present_queue)
```
Output:

```
result =  None
2017-10-18 16:21:19,156 vulkanbase_v3_recreateSwapChain._drawFrame                     +1625 : ERROR    Failed to present swapchain image!
```

**Comment by realitix** [comment]
Hello @sunbearc22, it's strange because this function can't return `None`. Can you show how you initialize 
```
self.fnp['vkQueuePresentKHR']
```

**Comment by sunbearc22** [comment]
Yes. I just uploaded my codes https://github.com/sunbearc22/vulkan_examples/blob/master/HelloTriangle/vulkanbase_v3_recreateSwapChain.py#L208. version 3 codes.

**Comment by realitix** [comment]
My last comment was wrong.
It's normal that it returns `None`. All functions return `None` with the wrapper. To catch the return value, you must use the exception system.
