### ISSUE TITLE
Issue with function _new in vulkan's __init__.py 

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#39]
Hi realitix...

There seem to be an issue in vulkan's `__init__.py`", line 2204, in function `_new`
```
    ret = ffi.new(_type.cname + '*', init)[0]
OverflowError: can't convert negative number to unsigned
```

My original code which used to work:
```
    def _createLogicalDevice(self):
        '''Create Logical Device'''

        #1. Create Logical Device Queue Create Info.
        queue_priorities = [1.0]
        queue_family_indices = {self.queue_families_graphics_index,
                                self.queue_families_present_index}
        # Note: queue_family_indices is a set; when it's items value are equal,
        #       set keeps only one of them. 
        logical_device_queues_createInfo = [ VkDeviceQueueCreateInfo(
            queueFamilyIndex = i,
            queueCount = 1,
            pQueuePriorities = queue_priorities)
                        for i in queue_family_indices ]
        logging.info('Created logical_device_queues_createInfo.')
```
the error is in listcomp
`    for i in queue_family_indices ]`

Can you let me know what is wrong and how I can fix it?

**Comment by sunbearc22** [comment]
I just noticed that my codes had all chosen to use my onboard Intel Skylake GPU as the physical device instead of using my Nvidia GPU. I got the same outcome from using your `example_sdl2.py` code and validation layer complained it can't create a surface. 

I recalled that my display driver was just upgrade to Nvidia 384.90 today from an earlier Nvidia driver. I suspect this may be an issue caused by the new display driver. Will check on this and update you.

**Comment by realitix** [comment]
Hello @sunbearc22, I wait for your update but indeed it seems related to your driver.

**Comment by sunbearc22** [comment]
Yes, the issue is caused by Ubuntu's nvidia-384 driver. Fortunately, users can quickly rectify the matter, while Ubuntu's graphics driver maintainer fix the mistake. More details given [here](https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-384/+bug/1726809).
