### ISSUE TITLE
example.py: queueFamilyIndices appears undefined (line 283) and typo in line 281 

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#4]
In examply.py line, it writes
`281        imageSharingMode = VK_SHARING_MODE_CONCURREN`
`283        pQueueFamilyIndices = queueFamilyIndices`

Issues:
1. There is a typo in 281, letter 'T" is missing: it should be `VK_SHARING_MODE_CONCURRENT`
2. The term `queueFamilyIndices` appears to be undefined. I believe `queueFamilyIndices = {queue_family_graphic_index, queue_family_present_index}` should either appear in line 279 or 183.

**Comment by realitix** [comment]
Thanks, it's fixed
