### ISSUE TITLE
No module named 'vulkan._vulkancache'

### ISSUE THREAD

**Issue by Tcll** [realitix/vulkan#41]
love the fact it's pretty much standalone, but there's an issue upon extraction.
![image](https://user-images.githubusercontent.com/773959/38751471-397a6330-3f26-11e8-860f-a691ea8f7a62.png)
I'm using x86 Windows Anaconda on Wine (Linux) for testing
CWD is `Z:\home\tcll\Downloads\vulkan-1.1.71.2\`

**Comment by Tcll** [comment]
quick correction from `_vulkancache` to `vulkan_build` gives me this:
![image](https://user-images.githubusercontent.com/773959/38751933-930b107e-3f27-11e8-9140-52148522ef2f.png)
this looks like it's something more on my end now, though I could be wrong ;)

**Comment by realitix** [comment]
Hello @Tcll,
Thanks for reporting your issue.

What version of `cffi` are you using ? Can you try with the last `cffi` version ?

**Comment by Tcll** [comment]
ah I was using the version that came with Anaconda 2.3.0 `cffi-1.1.0-py34_0`

I will work on downloading the updated wheels and set up a portable environment to see if that fixes the above issue.
thanks ;)

**Comment by realitix** [comment]
Nice! Glad to help you
