### ISSUE TITLE
Name changes to structs and functions that have been promoted from 1.0 to 1.1.

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#45]
I was reading [Spec 1.1.77.0](https://vulkan.lunarg.com/doc/view/1.1.77.0/windows/vkspec.html#vkEnumeratePhysicalDeviceGroups) and learnt about some changes in the naming of some functions and structs for Vulkan 1.0 to Vulkan 1.1. I also read [1.1.70.1 release notes](https://vulkan.lunarg.com/doc/sdk/1.1.70.1/windows/release_notes.html) and found the explanation for the naming changes. I believe  `_vulkan.py` in vulkan 1.1.71.2  is missing the following updates. There are still more to update. Apologies I could not get to all. There are like 23 occurrences of the phrase "Promotion to Vulkan 1.1"  in 1.1.70.1 spec. I only managed to go through 3 of them. 

### Some changes needed
```
VkPhysicalDeviceIDPropertiesKHR = VkPhysicalDeviceIDProperties
VkQueueFamilyProperties2KHR = VkQueueFamilyProperties2
VkPhysicalDeviceGroupPropertiesKHR = VkPhysicalDeviceGroupProperties
vkEnumeratePhysicalDeviceGroupsKHR = vkEnumeratePhysicalDeviceGroups
VkDeviceGroupDeviceCreateInfoKHR = VkDeviceGroupDeviceCreateInfo
VkPhysicalDeviceVariablePointerFeaturesKHR = VkPhysicalDeviceVariablePointerFeatures
VkPhysicalDeviceMultiviewFeaturesKHR = VkPhysicalDeviceMultiviewFeatures
VkPhysicalDeviceMultiviewPropertiesKHR = VkPhysicalDeviceMultiviewProperties
VkPhysicalDevice16BitStorageFeaturesKHR = VkPhysicalDevice16BitStorageFeatures
VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR = VkPhysicalDeviceSamplerYcbcrConversionFeatures
VkPhysicalDeviceMaintenance3Properties missing

VkMemoryDedicatedRequirementsKHR =  VkMemoryDedicatedRequirements
VkMemoryDedicatedAllocateInfoKHR = VkMemoryDedicatedAllocateInfo
VkBindBufferMemoryInfoKHR = VkBindBufferMemoryInfo
VkBindImageMemoryInfoKHR = VkBindImageMemoryInfo
vkBindBufferMemory2KHR = vkBindBufferMemory2
vkBindImageMemory2KHR = vkBindImageMemory2

VkDescriptorUpdateTemplateKHR = VkDescriptorUpdateTemplate
VkDescriptorUpdateTemplateCreateFlags missing
VkDescriptorUpdateTemplateType missing
VkDescriptorUpdateTemplateEntryKHR = VkDescriptorUpdateTemplateEntry
VkDescriptorUpdateTemplateCreateInfoKHR = VkDescriptorUpdateTemplateCreateInfo
vkCreateDescriptorUpdateTemplateKHR = vkCreateDescriptorUpdateTemplate
vkDestroyDescriptorUpdateTemplateKHR = vkDestroyDescriptorUpdateTemplate
vkUpdateDescriptorSetWithTemplateKHR = vkUpdateDescriptorSetWithTemplate
```

**Comment by realitix** [comment]
Thanks for the update, I have to update the generator.

**Comment by realitix** [comment]
I started to work on it today in the `new_version` branch.
It's not ready yet, I will let you know when it's done.

**Comment by sunbearc22** [comment]
Cheers. is the `new_version` branch visible? How do I see it?

**Comment by realitix** [comment]
Yes you can see this branch [here](https://github.com/realitix/vulkan/tree/new_version).
It's not ready yet, not so easy!

**Comment by sunbearc22** [comment]
Thank you. Sincerely.

**Comment by realitix** [comment]
The master has been updated to last sdk

**Comment by realitix** [comment]
I can close since I updated to last SDK.
