### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by apenngrace** [realitix/vulkan#51]
Do the versions of this repo necessarily track with the LunarG versions?  I see that this repo is currently at version 1.1.71.2.  LunarG's Vulkan SDK is now at 1.1.85.0 (as of Oct 2018).

By the way, if you are a Mac user, I created a vulkan installer for the homebrew package manager.  It can be installed with the command `brew cask install apenngrace/vulkan/vulkan-sdk`.  I have been testing this python wrapper on the Mac and so far so good!

**Comment by realitix** [comment]
Hello,
Indeed it's still active, I'm updating the generator because of the V1.1 of Vulkan and when it will be done I will upgrade to the last SDK Version.
Glad to see that it works well on Mac!

**Comment by apenngrace** [comment]
Any way I can help?

**Comment by realitix** [comment]
It's updated to 1.1.99!
