### ISSUE TITLE
Suggested condition for VkPipelineInputAssemblyStateCreateInfo

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#53]
Hi @realitix , according to Vulkan spec on [Drawing Commands](https://vulkan.lunarg.com/doc/view/1.1.85.0/windows/vkspec.html#drawing), `primitiveRestartEnable` must be `VK_FALSE` for certain topology.

I like to suggest appending [VkPipelineInputAssemblyStateCreateInfo](https://github.com/realitix/vulkan/blob/master/vulkan/_vulkan.py#L2534) with the below condition. What do you think?

```
def VkPipelineInputAssemblyStateCreateInfo(#sType=VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,pNext=None,flags=None,topology=None,primitiveRestartEnable=None,):
    disallow_primitiveRestartEnable = (0,1,3,6,8,10) ##new
    if topology in disallow_primitiveRestartEnable: primitiveRestartEnable=VK_FALSE ##new
        
    return _new('VkPipelineInputAssemblyStateCreateInfo', sType=sType,pNext=pNext,flags=flags,topology=topology,primitiveRestartEnable=primitiveRestartEnable)
```

**Comment by realitix** [comment]
Hello @sunbearc22, I would like to keep this wrapper as thin as possible.
It's the developer who must add this condition.

Thanks
