### ISSUE TITLE
example_sdl2.py has unstable FPS because it lacks completion fence/semaphores

### ISSUE THREAD

**Issue by buzmeg** [realitix/vulkan#58]
This is probably related to Bug #55 

In my instance, vkAcquireNextImageKHR burns through a handful of buffers at max speed, and then settles down to 60Hz (1 buffer every 16.6666666 ms).  I suspect that this would put a 10-15 frame latency in things I do if this were an active application rather than an example.

I'm on Windows 10, a Microsoft Surface Pro, with Intel UHD Graphics 620 via the external Surface dock to an LG 32UD99-W monitor via mini-Displayport and Vulkan SDK 1.1.114.0

The synchronization primitives used in the example don't seem to be sufficient to get stable and repeatable results on hardware.

I also did a grubby port to glfw to see if there was an SDL issue, GLFW exhibits the same behavior.

Thanks.

[main.py.zip](https://github.com/realitix/vulkan/files/3495883/main.py.zip)

**Comment by realitix** [comment]
Hello @buzmeg, I will take a look at your issue.
Thanks for submitting.

**Comment by realitix** [comment]
Hello, the test is just a sample to show it works. The developer then has to take care of utilization in order to get the maximum performance of Vulkan.
