### ISSUE TITLE
Vulkan 1.2.141.2

### ISSUE THREAD

**Issue by ompadu** [realitix/vulkan#66]
Hi @realitix , does the possibility exist to update the wrapper to the latest Vulkan version?
Thank you

**Comment by realitix** [comment]
Hello @ompadu.
Yes indeed there is no problem to update it.
You just have to update the files in `vulkan_include` folder in the `generator` and then launch `generate.py`.
I will do it when I have time but you can do it if you can't wait.

Thanks

**Comment by ompadu** [comment]
I don't mind updating it for myself.

Can it be done on windows? Last time I took a look at `generate.py` it seemed that it used a Linux utility.

**Comment by okuma10** [comment]
I tried to update it as well.
But got an error : 
```  File "C:\Users\Okuma_10\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified```
