### ISSUE TITLE
SDL2 example is now broken(easy to fix)

### ISSUE THREAD

**Issue by karbiv** [realitix/vulkan#68]
**Only** `VK_LAYER_KHRONOS_validation` is correct, ALL other validation layers are [deprecated](https://vulkan.lunarg.com/doc/view/1.1.114.0/windows/validation_layers.html).
With `VK_LAYER_LUNARG_standard_validation`, `vkCreateInstance` throws an error: _vulkan._vulkan.VkErrorLayerNotPresent_

https://github.com/realitix/vulkan/blob/ac83f887c3575892dc121376b5ac0c05076c4979/example/example_sdl2.py#L50-L55

It works on Manjaro(Arch) after editing line 54 to contain `VK_LAYER_KHRONOS_validation`.
_vulkan-icd-loader_ 1.2.148-1

**Comment by Freed-Wu** [comment]
I still met this bug:

```shell
❯ example/example_sdl2.py
availables extensions: ['VK_EXT_debug_report', 'VK_EXT_debug_utils']

availables layers: []

Traceback (most recent call last):
  File "/home/wzy/Desktop/vulkan/example/example_sdl2.py", line 78, in <module>
    instance = vkCreateInstance(createInfo, None)
  File "/usr/lib/python3.9/site-packages/vulkan/_vulkan.py", line 4983, in vkCreateInstance
    raise exception_codes[result]
vulkan._vulkan.VkErrorLayerNotPresent
```

OS: linux 5.13.13
python-vulkan: 1.1.99.1-1

**Comment by realitix** [comment]
Yon don't have any layer available so it's a problem on your environment.
