### ISSUE TITLE
Vulkan is Failing to Install on Windows 10

### ISSUE THREAD

**Issue by Program-The-World** [realitix/vulkan#69]
As I was writing this request for help, I found a fix for it, so I decided I might as well share the solution for my problem.
My problem was quite simply this: Vulkan wouldn't install through the `pip install vulkan` command. It would download the package, wait about fifteen seconds, then it would spit out a big error.

I was stuck on this for a few days, then I ran into a fix on a github issue for an entirely different package.
Essentially, before you try installing Vulkan, run `pip install --upgrade pip setuptools wheel` and the installation should work just fine for Vulkan.

Perhaps Realitix could add a small section in the readme file telling the user that if the installation doesn't work, they can try running the above command before attempting to install again?

(nice)

**Comment by Program-The-World** [comment]
Hey @realitix , yes, I did experience this issue on Windows 10.

**Comment by realitix** [comment]
Thanks @Program-The-World, I updated the README.
