### ISSUE TITLE
VkWin32SurfaceCreateInfoKHR not defined in Windows Vulkan DLL

### ISSUE THREAD

**Issue by griffin2000** [realitix/vulkan#7]
The structure VkWin32SurfaceCreateInfoKHR is not defined in the Windows DLL (Nvidia drivers Windows 8.1).

The result is this error in the example code:

```
Create windows surface
Traceback (most recent call last):
  File "example.py", line 145, in <module>
    surface = surface_mapping[wm_info.subsystem]()
  File "example.py", line 137, in surface_win32
    flags=0)
  File "E:\Python\Python35\lib\site-packages\vulkan-1.0.48-py3.5.egg\vulkan\__init__.py", line 2113, in VkWin32SurfaceCreateInfoKHR
    return _new('VkWin32SurfaceCreateInfoKHR', sType=sType,pNext=pNext,flags=flags,hinstance=hinstance,hwnd=hwnd)
  File "E:\Python\Python35\lib\site-packages\vulkan-1.0.48-py3.5.egg\vulkan\__init__.py", line 1831, in _new
    _type = ffi.typeof(ctype)
ffi.error: undefined type name
VkWin32SurfaceCreateInfoKHR
^
```

**Comment by realitix** [comment]
Fixed in 1.0.49.

Thanks

**Comment by griffin2000** [comment]
Is this definitely fixed? I still don't see that vkCreateWin32SurfaceKHR in the file. I think there will need to a different file (or FFI object) for each platform. How is that FFI data generated?

**Comment by realitix** [comment]
You can fint it here for runtime: https://github.com/realitix/vulkan/blob/master/vulkan/__init__.py#L4209
And here for generation https://github.com/realitix/vulkan/blob/master/_cffi_build/vulkan.cdef.h#L3321

Where are you looking at ?

**Comment by griffin2000** [comment]
Oh yeah, quite right. Didn't update correctly, running now for me.
