### ISSUE TITLE
Errors out

### ISSUE THREAD

**Issue by AwesomeNoob999** [realitix/vulkan#72]
I am using the example_sdl2.py and it pops up this in the terminal and kills the window.
Logical device and graphic queue successfully created
selected format: 44
3 available swapchain present modes
5 images view created
XIO:  fatal IO error 0 (Success) on X server ":0.0"
      after 194 requests (194 known processed) with 36 events remaining.

**Comment by realitix** [comment]
Hello @AwesomeNoob999,
The problem comes from you X server. I can't help you on this, it's not directly related to `vulkan`.

Sorry.
