### ISSUE TITLE
example.py "ffi" undefined

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#8]
https://github.com/realitix/vulkan/blob/master/example/example.py#L647 gives
`submit_list = ffi.new('VkSubmitInfo[1]', [submit_create])`

I think there is a problem here: `ffi` has not been defined. 
https://github.com/realitix/vulkan/blob/master/example/example.py#L124 did define `_ffi` but not `ffi`. Also, `_ffi`  is only defined for Windows OS and not for any other platform.

**Comment by realitix** [comment]
Hello @sunbearc22, it's not an error, the ffi variable is imported with `from vulkan import *`.
That's why we should never user `import *` ! But it's just an example file, that's why I did it.
