### ISSUE TITLE
Update version available on PyPi

### ISSUE THREAD

**Issue by imandresilva** [realitix/vulkan#81]
The version currently available on PyPi doesn't work with Python > 3.8.
There have been multiple changes and tags since the last one available on PyPi, some of which seem to fix problems originated from the more recent versions of Python.

**Comment by dcmvdbekerom** [comment]
I'm in the same boat, any idea when the updated wheel will be on pypi?

**Comment by realitix** [comment]
Hello, I have to do it but not a lot of time for that.

**Comment by realitix** [comment]
I just did a test on master and I have a problem with sdl which doesn't recognize the plateform.

**Comment by realitix** [comment]
It's done. Last version of Vulkan supported
